### ISSUE TITLE
css transport format

### ISSUE THREAD

**Issue by lepture** [spmjs/spm2#4]
Before transport:

``` css
@import url("base");

body {
    color: black;
}

@import url("button");
```

After transport:

``` css
/*! define family/name/version/filename.css */
/*! import alice/base/1.0.0/base.css */

body {
    color: black;
}

/*! import alice/button/1.0.0/button.css */
```

After concat:

``` css
/*! define family/name/version/filename.css */
/*! block alice/base/1.0.0/base.css */
body {
    content: 'base';
}
/*! endblock alice/base/1.0.0/base.css */

body {
    color: black;
}

/*! block alice/button/1.0.0/button.css */
body {
   content: 'button';
}
/*! endblock alice/button/1.0.0/button.css */
```
